# Generated by Django 5.1 on 2024-09-23 05:06

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Connection Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_registration', models.BooleanField(default=False, verbose_name='User Registration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('domain_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.DomainNameValidator()], verbose_name='Domain Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.company'),
        ),
        migrations.CreateModel(
            name='RedshiftConnection',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.connection')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('database', models.CharField(max_length=255, verbose_name='Database')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('app.connection',),
        ),
        migrations.CreateModel(
            name='SnowflakeConnection',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.connection')),
                ('account', models.CharField(max_length=255, verbose_name='Account')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Warehouse')),
                ('database', models.CharField(blank=True, max_length=255, null=True, verbose_name='Database')),
                ('schema', models.CharField(blank=True, max_length=255, null=True, verbose_name='Schema')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('app.connection',),
        ),
        migrations.AddField(
            model_name='connection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.company')),
                ('permissions', models.ManyToManyField(blank=True, related_name='custom_group_set', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='app.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('type', models.CharField(choices=[('RECONNAISSANCE', 'Reconnaissance (1 Connection)'), ('TEST', 'Test')], default='RECONNAISSANCE', max_length=127, verbose_name='Task type')),
                ('recurrence_interval', models.IntegerField(choices=[(0, 'Never'), (3600, 'Hourly'), (86400, 'Daily'), (604800, 'Weekly'), (2419200, 'Monthly')], default=0, verbose_name='Interval')),
                ('run_at', models.DateTimeField(verbose_name='Start At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='tasks', to='app.connection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Argument Name')),
                ('value', models.CharField(max_length=255, verbose_name='Argument Value')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='app.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('run_type', models.CharField(max_length=127, verbose_name='Task run type')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('log', models.FileField(blank=True, null=True, upload_to='', verbose_name='Log')),
                ('output', models.FileField(blank=True, null=True, upload_to='', verbose_name='Output')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.task')),
            ],
        ),
    ]
