# Generated by Django 5.1 on 2024-09-23 05:06

from django.db import migrations
from app.models import User, Setting

def add_default_superuser(apps, schema_editor):
    User.objects.create_superuser( 'glen.rodrigues@wissen.com', 'password', name='Glen Rodrigues')

def create_default_settings(apps, schema_editor):
    Setting.load()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_superuser),
        migrations.RunPython(create_default_settings),
    ]
